export const coreOpsStaffImprovements = [
  {
    id: "role-based-permissions-matrix",
    title: "Role-Based Permissions Matrix",
    category: "Access Control",
    priority: "P0",
    owner: "Management Operations",
    riskLevel: "High",
    description: "Define every staff role against allowed actions so operators only receive the access their work requires.",
    controls: ["role templates", "scope editor", "least-privilege review", "permission diff"],
    queues: ["access review", "staff setup"],
    metrics: ["overprivileged accounts", "pending reviews", "revoked scopes"],
    staffActions: ["grant scope", "revoke scope", "request manager review", "export matrix"],
    userVisibleStatus: "Not visible to members.",
    requiresApproval: true
  },
  {
    id: "case-management-center",
    title: "Case Management Center",
    category: "Support Operations",
    priority: "P0",
    owner: "Support Operations",
    riskLevel: "High",
    description: "Unify disputes, fraud reports, safety reports, appeals, recovery requests, privacy requests, and payment issues.",
    controls: ["case intake", "owner assignment", "priority selector", "status workflow", "case notes"],
    queues: ["support", "fraud", "safety", "appeals", "account recovery", "payments", "privacy"],
    metrics: ["open cases", "overdue cases", "average resolution time", "reopen rate"],
    staffActions: ["assign case", "escalate case", "request evidence", "resolve case", "reopen case"],
    userVisibleStatus: "Members see received, under review, waiting on info, resolved, or appealed.",
    requiresApproval: false
  },
  {
    id: "staff-action-approval-flow",
    title: "Staff Action Approval Flow",
    category: "Governance",
    priority: "P0",
    owner: "Trust Governance",
    riskLevel: "Critical",
    description: "Require second approval for sensitive actions that can restrict users, move funds, or change staff power.",
    controls: ["approval request", "second-review queue", "risk summary", "decision log"],
    queues: ["high-risk approvals", "manager review"],
    metrics: ["approval wait time", "denied approvals", "approved high-risk actions"],
    staffActions: ["request approval", "approve action", "deny action", "add approval note"],
    userVisibleStatus: "Members see action pending review when the decision affects their account.",
    requiresApproval: true
  },
  {
    id: "staff-audit-search",
    title: "Staff Audit Search",
    category: "Audit",
    priority: "P1",
    owner: "Compliance Operations",
    riskLevel: "High",
    description: "Search staff activity by operator, member, case, action, date, severity, status, and outcome.",
    controls: ["audit filters", "saved searches", "timeline view", "export controls"],
    queues: ["audit review", "compliance export"],
    metrics: ["searches run", "flagged actions", "exported logs"],
    staffActions: ["search audit log", "open audit detail", "flag action", "export results"],
    userVisibleStatus: "Not visible to members unless exported for a privacy or legal request.",
    requiresApproval: false
  },
  {
    id: "escalation-rules",
    title: "Escalation Rules",
    category: "Routing",
    priority: "P0",
    owner: "Operations Management",
    riskLevel: "High",
    description: "Route high-risk or specialized issues to the right staff team before they stall or reach the wrong queue.",
    controls: ["routing rules", "severity matcher", "team handoff", "override reason"],
    queues: ["fraud ops", "security", "legal and privacy", "trust and safety", "management"],
    metrics: ["auto-escalations", "manual escalations", "misrouted cases", "handoff time"],
    staffActions: ["escalate to team", "accept escalation", "return case", "update routing rule"],
    userVisibleStatus: "Members see escalated for specialist review.",
    requiresApproval: false
  },
  {
    id: "staff-performance-dashboard",
    title: "Staff Performance Dashboard",
    category: "Operations Analytics",
    priority: "P1",
    owner: "Operations Management",
    riskLevel: "Medium",
    description: "Track workload, response speed, quality, reversals, overdue work, and post-resolution satisfaction.",
    controls: ["team dashboard", "operator scorecard", "queue load view", "quality signals"],
    queues: ["performance review", "quality review"],
    metrics: ["cases resolved", "average first response", "overdue cases", "reversal rate", "satisfaction score"],
    staffActions: ["review operator load", "rebalance cases", "mark coaching needed", "export performance"],
    userVisibleStatus: "Not visible to members.",
    requiresApproval: false
  },
  {
    id: "user-facing-case-status-sync",
    title: "User-Facing Case Status Sync",
    category: "Member Transparency",
    priority: "P0",
    owner: "Support Operations",
    riskLevel: "Medium",
    description: "Sync a safe status summary from staff workflows to members without exposing internal notes or risk signals.",
    controls: ["public status mapping", "safe summary editor", "member update log", "notification toggle"],
    queues: ["member updates", "waiting on member"],
    metrics: ["status updates sent", "member response time", "stale public statuses"],
    staffActions: ["send status update", "request member info", "hide internal note", "close public thread"],
    userVisibleStatus: "Members see plain-language status, requested next steps, and final outcome.",
    requiresApproval: false
  },
  {
    id: "sensitive-data-access-controls",
    title: "Sensitive Data Access Controls",
    category: "Privacy and Security",
    priority: "P0",
    owner: "Security Operations",
    riskLevel: "Critical",
    description: "Require staff to provide a business reason before viewing sensitive member, payment, device, or private message data.",
    controls: ["reason prompt", "masked default view", "break-glass access", "automatic audit event"],
    queues: ["sensitive access review", "security review"],
    metrics: ["sensitive views", "missing reasons", "break-glass events", "review flags"],
    staffActions: ["request data view", "mask data", "approve break-glass", "flag suspicious access"],
    userVisibleStatus: "Members can see that sensitive access is audited, without exposing staff-only investigations.",
    requiresApproval: true
  },
  {
    id: "staff-training-policy-library",
    title: "Staff Training / Policy Library",
    category: "Knowledge Management",
    priority: "P1",
    owner: "Policy Operations",
    riskLevel: "Medium",
    description: "Provide searchable policy, moderation standards, fraud playbooks, privacy rules, macros, and training checks.",
    controls: ["policy search", "playbook library", "macro library", "knowledge checks", "version history"],
    queues: ["training review", "policy updates"],
    metrics: ["policy views", "completed checks", "outdated articles", "macro usage"],
    staffActions: ["open policy", "attach policy version", "complete check", "suggest policy update"],
    userVisibleStatus: "Members may see public policy summaries, not internal playbooks.",
    requiresApproval: false
  },
  {
    id: "incident-command-mode",
    title: "Incident Command Mode",
    category: "Incident Response",
    priority: "P0",
    owner: "Incident Commander",
    riskLevel: "Critical",
    description: "Coordinate major events such as scam spikes, outages, harmful content waves, compromised staff accounts, and payment failures.",
    controls: ["incident room", "severity level", "timeline", "action checklist", "status broadcast"],
    queues: ["active incidents", "postmortem review"],
    metrics: ["time to detect", "time to mitigate", "impacted users", "follow-up tasks"],
    staffActions: ["open incident", "assign commander", "freeze risky action", "publish status", "close incident"],
    userVisibleStatus: "Members see service status and safety advisories when public communication is required.",
    requiresApproval: true
  }
];
