export const riskQualityStaffImprovements = [
  {
    id: 21,
    title: "Staff Account Security Panel",
    category: "security",
    priority: "critical",
    owner: "Security Operations",
    riskLevel: "high",
    description: "Central view of staff MFA, devices, sessions, last login, role age, and suspicious access signals.",
    controls: ["MFA enforcement", "device session review", "inactive staff flagging", "role age review"],
    queues: ["staff-security-review", "suspicious-staff-login"],
    metrics: ["mfaCoverageRate", "staleSessionCount", "inactiveStaffAccounts", "suspiciousLoginAlerts"],
    staffActions: ["revokeSession", "requireMfaReset", "suspendStaffAccess", "requestManagerReview"],
    userVisibleStatus: "Not visible to members.",
    requiresApproval: true,
  },
  {
    id: 22,
    title: "SLA Timers",
    category: "support-operations",
    priority: "high",
    owner: "Support Operations",
    riskLevel: "medium",
    description: "Timers for support, fraud, appeals, payments, privacy, and safety cases with breach warnings.",
    controls: ["case deadline tracking", "breach alerts", "queue aging", "priority timers"],
    queues: ["overdue-support", "overdue-appeals", "overdue-fraud-review"],
    metrics: ["averageTimeToFirstResponse", "averageResolutionTime", "slaBreachCount", "oldestOpenCaseAge"],
    staffActions: ["escalateOverdueCase", "reassignCase", "pauseTimerWithReason", "markSlaMet"],
    userVisibleStatus: "Members can see simple status milestones and expected review windows.",
    requiresApproval: false,
  },
  {
    id: 23,
    title: "Auto-Prioritization",
    category: "queue-management",
    priority: "high",
    owner: "Operations Management",
    riskLevel: "medium",
    description: "Ranks work by user harm, payment risk, legal exposure, safety severity, age, and repeat reports.",
    controls: ["priority scoring", "severity bands", "aging boost", "risk-based routing"],
    queues: ["critical-priority", "high-risk-payment", "member-harm-review"],
    metrics: ["criticalQueueDepth", "priorityAccuracyRate", "manualPriorityOverrides", "timeToTriage"],
    staffActions: ["overridePriority", "assignPriorityOwner", "escalateCriticalCase", "downgradeWithReason"],
    userVisibleStatus: "Members see priority status only when it affects response timing.",
    requiresApproval: false,
  },
  {
    id: 24,
    title: "User Communication Templates",
    category: "support-quality",
    priority: "high",
    owner: "Customer Support",
    riskLevel: "low",
    description: "Approved responses for evidence requests, holds, approvals, denials, appeals, and recoveries.",
    controls: ["template library", "reason-code merge fields", "tone review", "localized variants"],
    queues: ["template-review", "outbound-message-quality"],
    metrics: ["templateUsageRate", "responseEditRate", "memberSatisfactionAfterReply", "reopenedAfterReply"],
    staffActions: ["sendTemplate", "requestTemplateUpdate", "attachReasonCode", "saveCaseSummary"],
    userVisibleStatus: "Members receive clear case updates without internal notes.",
    requiresApproval: false,
  },
  {
    id: 25,
    title: "Escalation Tree",
    category: "operations-routing",
    priority: "critical",
    owner: "Operations Management",
    riskLevel: "high",
    description: "Defined routing from support to trust, fraud, security, payments, legal, privacy, or managers.",
    controls: ["routing rules", "handoff requirements", "escalation ownership", "manager override"],
    queues: ["trust-escalations", "fraud-escalations", "legal-privacy-escalations", "manager-review"],
    metrics: ["escalationVolume", "handoffCompletionRate", "misrouteRate", "timeInEscalation"],
    staffActions: ["escalateCase", "acceptHandoff", "rejectWithReason", "assignEscalationOwner"],
    userVisibleStatus: "Members see that a case moved to specialist review.",
    requiresApproval: false,
  },
  {
    id: 26,
    title: "Quality Assurance Sampling",
    category: "quality-assurance",
    priority: "medium",
    owner: "Quality Assurance",
    riskLevel: "medium",
    description: "Random and risk-based sampling of closed cases for manager review and coaching.",
    controls: ["sampling rules", "review scorecards", "coaching flags", "closed-case audits"],
    queues: ["qa-sample-review", "coaching-needed", "decision-consistency-review"],
    metrics: ["qaSampleRate", "qaPassRate", "coachingFlagCount", "repeatDecisionDefects"],
    staffActions: ["sampleClosedCase", "scoreReview", "requestCoaching", "flagPolicyGap"],
    userVisibleStatus: "Not visible unless a case outcome changes after review.",
    requiresApproval: false,
  },
  {
    id: 27,
    title: "Staff Notes Privacy Levels",
    category: "privacy",
    priority: "critical",
    owner: "Privacy Operations",
    riskLevel: "high",
    description: "Separates notes into internal, manager-only, legal-only, and user-visible summaries.",
    controls: ["note classification", "restricted visibility", "user-visible summary", "redaction prompt"],
    queues: ["restricted-note-review", "user-summary-review", "privacy-redaction-review"],
    metrics: ["restrictedNoteCount", "misclassifiedNoteRate", "summaryCoverageRate", "redactionRequests"],
    staffActions: ["classifyNote", "redactNote", "publishUserSummary", "requestPrivacyReview"],
    userVisibleStatus: "Members can see approved summaries, not internal restricted notes.",
    requiresApproval: true,
  },
  {
    id: 28,
    title: "Policy Versioning",
    category: "compliance",
    priority: "high",
    owner: "Policy and Compliance",
    riskLevel: "medium",
    description: "Attaches the active policy version to moderation, fraud, support, and appeal decisions.",
    controls: ["policy version stamp", "decision reason mapping", "policy change log", "legacy decision lookup"],
    queues: ["policy-gap-review", "outdated-policy-action", "appeal-policy-check"],
    metrics: ["decisionsWithPolicyVersion", "policyMismatchCount", "appealsByPolicyVersion", "policyUpdateLag"],
    staffActions: ["attachPolicyVersion", "requestPolicyReview", "comparePolicyVersions", "flagOutdatedDecision"],
    userVisibleStatus: "Members can see the public policy reason used for a decision.",
    requiresApproval: false,
  },
  {
    id: 29,
    title: "Incident Postmortems",
    category: "incident-management",
    priority: "high",
    owner: "Incident Command",
    riskLevel: "high",
    description: "Records timeline, root cause, impact, staff actions, user impact, and follow-up tasks after major incidents.",
    controls: ["incident timeline", "root-cause notes", "impact summary", "follow-up ownership"],
    queues: ["postmortem-required", "incident-follow-up", "leadership-review"],
    metrics: ["postmortemCompletionRate", "timeToPostmortem", "followUpClosureRate", "repeatIncidentRate"],
    staffActions: ["openPostmortem", "assignFollowUp", "publishInternalSummary", "markCorrectiveActionDone"],
    userVisibleStatus: "Members may see a public status summary when appropriate.",
    requiresApproval: true,
  },
  {
    id: 30,
    title: "Abuse Pattern Detection",
    category: "trust-and-safety",
    priority: "critical",
    owner: "Trust and Safety",
    riskLevel: "high",
    description: "Detects repeated reports, coordinated abuse, scam rings, duplicate devices, and linked payout patterns.",
    controls: ["pattern flags", "linked-entity graph", "coordinated report checks", "scam-ring review"],
    queues: ["abuse-pattern-review", "coordinated-reporting", "linked-account-risk", "scam-ring-investigation"],
    metrics: ["patternAlertCount", "confirmedAbusePatterns", "falsePositiveRate", "linkedAccountCount"],
    staffActions: ["openPatternInvestigation", "linkRelatedCases", "applyFraudHold", "clearFalsePositive"],
    userVisibleStatus: "Members see only case-specific safety or enforcement status.",
    requiresApproval: true,
  },
];
