export const workflowIntelStaffImprovements = [
  {
    id: "staff-inbox",
    title: "Staff Inbox",
    category: "workflow",
    priority: "high",
    owner: "Support Operations",
    riskLevel: "medium",
    description: "Central inbox for assigned cases, mentions, approvals, escalations, and overdue work.",
    controls: ["assignment filters", "mention tracking", "overdue alerts"],
    queues: ["assigned cases", "approval requests", "escalations"],
    metrics: ["unread items", "overdue count", "average first response"],
    staffActions: ["open case", "assign owner", "escalate item", "mark reviewed"],
    userVisibleStatus: "No direct user status; synced through the related case.",
    requiresApproval: false
  },
  {
    id: "shift-handoff-notes",
    title: "Shift Handoff Notes",
    category: "operations",
    priority: "high",
    owner: "Operations Management",
    riskLevel: "medium",
    description: "Structured notes for open incidents, risky accounts, unresolved appeals, and payment holds.",
    controls: ["handoff template", "queue summary", "incident pinning"],
    queues: ["open incidents", "unresolved appeals", "payment holds"],
    metrics: ["handoff completion", "open risk items", "missed follow-ups"],
    staffActions: ["create handoff", "pin risk", "acknowledge shift", "assign follow-up"],
    userVisibleStatus: "No direct user status; prevents delays across staff shifts.",
    requiresApproval: false
  },
  {
    id: "internal-staff-chat",
    title: "Internal Staff Chat",
    category: "collaboration",
    priority: "medium",
    owner: "Staff Operations",
    riskLevel: "medium",
    description: "Staff-only case discussion tied to users, disputes, incidents, and policy decisions.",
    controls: ["case-linked threads", "private mentions", "retention labels"],
    queues: ["case discussions", "incident rooms", "policy questions"],
    metrics: ["open threads", "response latency", "unresolved mentions"],
    staffActions: ["start thread", "mention team", "link evidence", "close discussion"],
    userVisibleStatus: "Hidden from users; public summaries must be written separately.",
    requiresApproval: false
  },
  {
    id: "saved-views",
    title: "Saved Views",
    category: "workflow",
    priority: "medium",
    owner: "Support Operations",
    riskLevel: "low",
    description: "Reusable queue filters for high-risk fraud, overdue appeals, recovery, and payment disputes.",
    controls: ["filter builder", "shared views", "personal views"],
    queues: ["fraud views", "appeal views", "payment views", "recovery views"],
    metrics: ["view usage", "queue coverage", "stale view count"],
    staffActions: ["save filter", "share view", "set default", "archive view"],
    userVisibleStatus: "No direct user status.",
    requiresApproval: false
  },
  {
    id: "bulk-actions",
    title: "Bulk Actions",
    category: "workflow",
    priority: "medium",
    owner: "Operations Management",
    riskLevel: "high",
    description: "Apply low-risk queue changes across multiple cases while blocking sensitive mass actions.",
    controls: ["action preview", "scope limiter", "audit confirmation"],
    queues: ["low-risk review", "bulk assignment", "bulk closure"],
    metrics: ["bulk action count", "items changed", "reversal rate"],
    staffActions: ["bulk assign", "bulk mark reviewed", "bulk escalate", "bulk close"],
    userVisibleStatus: "Users see status changes only on affected cases.",
    requiresApproval: true
  },
  {
    id: "evidence-locker",
    title: "Evidence Locker",
    category: "case intelligence",
    priority: "high",
    owner: "Trust and Safety",
    riskLevel: "high",
    description: "Case evidence store for screenshots, reports, transaction IDs, chat excerpts, and device signals.",
    controls: ["evidence labels", "chain of custody", "restricted access"],
    queues: ["evidence review", "missing evidence", "restricted evidence"],
    metrics: ["evidence attached", "missing evidence rate", "access events"],
    staffActions: ["attach evidence", "classify evidence", "request evidence", "lock evidence"],
    userVisibleStatus: "Users may see evidence request status, not internal evidence notes.",
    requiresApproval: true
  },
  {
    id: "member-timeline-view",
    title: "Member Timeline View",
    category: "case intelligence",
    priority: "high",
    owner: "Support Operations",
    riskLevel: "high",
    description: "Staff-only chronological view of signup, reports, disputes, payments, warnings, appeals, and devices.",
    controls: ["timeline filters", "sensitive-data masking", "reason required"],
    queues: ["timeline review", "account recovery", "repeat issue analysis"],
    metrics: ["timeline views", "reason coverage", "case resolution impact"],
    staffActions: ["view timeline", "filter events", "link case", "flag pattern"],
    userVisibleStatus: "No direct user status; case summaries may reference verified events.",
    requiresApproval: true
  },
  {
    id: "risk-reason-explainer",
    title: "Risk Reason Explainer",
    category: "risk intelligence",
    priority: "high",
    owner: "Fraud and Risk",
    riskLevel: "high",
    description: "Explains why a case or user was flagged, including velocity, duplicate reports, device risk, or payment mismatch.",
    controls: ["reason codes", "confidence labels", "staff-only explanations"],
    queues: ["risk explanation", "false-positive review", "risk override"],
    metrics: ["flag volume", "false-positive rate", "override rate"],
    staffActions: ["view reasons", "confirm risk", "override flag", "request review"],
    userVisibleStatus: "Users see plain status, not full risk signals.",
    requiresApproval: true
  },
  {
    id: "appeal-quality-review",
    title: "Appeal Quality Review",
    category: "quality assurance",
    priority: "medium",
    owner: "Trust and Safety Management",
    riskLevel: "medium",
    description: "Tracks whether staff decisions are upheld, reversed, or need coaching after appeals.",
    controls: ["review sampling", "reversal reasons", "coaching notes"],
    queues: ["appeal QA", "reversal review", "manager coaching"],
    metrics: ["upheld rate", "reversal rate", "coaching required"],
    staffActions: ["review decision", "mark upheld", "mark reversed", "assign coaching"],
    userVisibleStatus: "Users see final appeal outcome and case status.",
    requiresApproval: false
  },
  {
    id: "staff-permission-change-log",
    title: "Staff Permission Change Log",
    category: "governance",
    priority: "high",
    owner: "Management",
    riskLevel: "high",
    description: "Dedicated log for staff invites, role changes, admin grants, access revocation, and scope edits.",
    controls: ["immutable log", "role diff", "manager review"],
    queues: ["permission changes", "admin grants", "revoked access"],
    metrics: ["permission changes", "admin grants", "revocations", "unreviewed changes"],
    staffActions: ["review change", "approve role", "revoke access", "export log"],
    userVisibleStatus: "No member-facing status; staff may see their own access changes.",
    requiresApproval: true
  }
];
